# Ingress Configuration
# This file defines the Ingress resource for the application, handling external access and SSL termination.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress
  annotations:
    # Use NGINX as the Ingress controller
    kubernetes.io/ingress.class: nginx
    # Use the 'letsencrypt-prod' ClusterIssuer to obtain SSL certificates
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Force SSL redirection
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    # Domain where the application will be accessible
    - 34.197.168.162.nip.io
    # Secret where the TLS certificate will be stored
    secretName: application-tls
  rules:
  - host: 34.197.168.162.nip.io
    http:
      paths:
      # Route for the frontend application
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      # Route for the backend API
      - path: /pipelines
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 8000
